apiVersion: v1
kind: Service
metadata:
  name: task-app-service
  namespace: sunil3gs98
  labels:
    app: task
spec:
  selector:
    app: task
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
