apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app
  namespace: sunil3gs98
  labels:
    app: task
spec:
  replicas: 4
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: santa
        image: sunil3gs98/task-master-pro:v1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://task-db-service:3306/taskdb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
