apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: sunil3gs98
  labels:
    app: task-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
