apiVersion: v1
kind: Service
metadata:
  name: task-db-service
  namespace: sunil3gs98
  labels:
    app: task-db
spec:
  selector:
    app: task-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer
